### ISSUE TITLE
Could you add a dialog with notes when click the status buttons?

### ISSUE THREAD

**Issue by archonwang** [lazureykis/redmine_status_buttons#1]
sometimes we need add some notes and other custom fields  with status such as Rejected. Could you Please add a new feature like this. Thanks so much.

**Comment by lazureykis** [comment]
No, this plugin will not support custom fields. The main goal is to keep simplicity.

Anyway, if your workflow requires custom fields to be filled, you will be redirected to issue form.

**Comment by archonwang** [comment]
OK, thanks for your reply.
